[package]
name = "rust_map"
version = "0.1.0"
authors = ["Dag Andersen <dagbjerreandersen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7.0"
bytes = "0.3.0"
regex = "1.1"
bincode = "1.0"