name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: |
        mkdir -p testdata/in/
        mkdir -p testdata/out/tree
        mkdir -p testdata/out/redblack
        mkdir -p testdata/out/table
        mkdir -p testdata/out/speed
        cargo test --release -- --test-threads 1
